steps:
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pip', 'install', '--upgrade', 'pip']
    - name: 'python'
      entrypoint: 'python'
      args: ['-m', 'pytest', '-vv', '--cov=hello', 'test_hello.py']

timeout: "1600s"
